name: Github Actions Test. Docker build and push

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Print a Random String
      run: echo "Hello Actions !!"

    - name: Build and push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: abhishekphukan/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

  Post-Build:
    needs: Build
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Print a String
      run: echo "This will wait for the Build-test to execute first"


  Parallel-Build:
    runs-on: ubuntu-latest

    steps:

    - name: Print a string
      run: echo "This step needs to run parallel. Default Behavior !!"
