name: Docker build and push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build-test:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print a Random String
      run: echo "Hello Actions !!"
